baseURL = "https://simonesanfilippo.xyz/"  # URL del tuo sito
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'simonesanfilippo_theme'
paginate = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
